### PR TITLE
Pass options to node-glob, fixes #37

### LINKED ISSUE #37: Pass through options to node-glob
This is related to why I bumped into #36  

It would be good to pass the Options object key/values that are not Sigh specific down to [node-glob options](https://github.com/isaacs/node-glob#options).

In particular I'd like to have access to the 'ignore' option since otherwise (as far as I know) there is unnecessary walking at the globbing stage to exclude folders or files - if they needs to then be rejected afterwards with the sigh-reject/filter module.

### PR DESCRIPTION
**Pull request by jmatsushita**
Let me know what you think! #37

### CODE REVIEW

**Comment by jmatsushita** [comment]
Looks like I broke the basePath option. Looking into it.

**Comment by ohjames** [comment]
I see you added a couple more commits, did you fix the issue with the basePath option?

**Comment by ohjames** [comment]
I think it would also be better to pass the entire options in to a second field like um `globOpts: {}` rather than deleting all `glob` plugin specific fields from the option and passing it through.

**Comment by jmatsushita** [comment]
Sorry for the delay here. Yes indeed I fixed the issue and I agree that a globOpts key would be much cleaner. Feel free to close this pull request which I should have started from my master anyway :)

**Pull request closed without merging**
