### PR TITLE
Guard against empty sourceMap, fixes #39

### LINKED ISSUE #39: TypeError: Cannot read property 'map' of undefined
I'm getting this error message without further information...
```
$ sigh build-test -vvvvv
 * running pipelines [ build-test ] with 3 jobs
 * waiting for subprocesses to start
 * subprocesses started in 0.852 seconds
 ! error: pipeline build-test
 ! TypeError: Cannot read property 'map' of undefined
 * pipeline(s) complete: 4.103 seconds
```

It happens with a large file tree and I think in the write plugin.

### PR DESCRIPTION
**Pull request by jmatsushita**
#39

### CODE REVIEW

**Comment by ohjames** [comment]
This change breaks two tests, maybe due to the line note I added. Pretty sure the patch is unnecessary after the latest sigh.

**Comment by jmatsushita** [comment]
Test now passing but with a warning on the concat plugin:
```
 ! could not construct identity source map for subdir/output.js
 ! Line 1: Unexpected token ILLEGAL
```

**Comment by ohjames** [comment]
@jmatsushita Yeah that warning is annoying since it alerts the console, last night I tried to stub `sigh-core`'s log using sinon but it didn't seem to work.

**Comment by ohjames** [comment]
@jmatsushita Oh and could you squash your commits together so I can merge this. Thanks!

**Pull request closed without merging**
